### ISSUE TITLE
link to assertive in README

### ISSUE THREAD

**Issue by richierocks** [egnha/valaddin#15]
Any chance of a link to the `assertive` package in the Related Packages section of the README?

- [`assertive`](https://bitbucket.org/richierocks/assertive) provides over 400 functions for checking common code problems. It is optimized for clarity of code and clarity of error messages.

You might also want to link to Michel Lang's [`checkmate`](https://github.com/mllg/checkmate) package.

**Comment by egnha** [comment]
Thanks for bringing these to my attention. I've added links to the README and vignette.
